name: CI

on:
  push:
    branches:
      - main
      - next
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          node-version: 16.x
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint && pnpm run build

      # - name: Test
      #   env:
      #     PM_SECRET_KEY: ${{ secrets.PM_SECRET_KEY }}
      #     PM_WEBHOOK_ID: ${{ secrets.PM_WEBHOOK_ID }}
      #     PM_LINK_ID: ${{ secrets.PM_LINK_ID }}
      #     PM_LINK_REF: ${{ secrets.PM_LINK_REF }}
      #     PM_PAYMENT_ID: ${{ secrets.PM_PAYMENT_ID }}
      #   run: pnpm test --clearCache && pnpm test --ci --coverage --maxWorkers=2
