name: CI

on:
  push:
    branches:
      - main
      - next
      - dev

jobs:
  build:
    name: Build, lint, and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Use Node.js latest
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "pnpm"

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Test
        env:
          PM_SECRET_KEY: ${{ secrets.PM_SECRET_KEY }}
          PM_WEBHOOK_ID: ${{ secrets.PM_WEBHOOK_ID }}
          PM_LINK_ID: ${{ secrets.PM_LINK_ID }}
          PM_LINK_REF: ${{ secrets.PM_LINK_REF }}
          PM_PAYMENT_ID: ${{ secrets.PM_PAYMENT_ID }}
        run: pnpm test

      - name: Build
        run: pnpm build
